on: push 
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Print something
        run: echo " José Antonio Mendoza Navarro"
      - name:  Print something 2
        run: echo "Expediente 736418"